#!/bin/sh

function pause()
{
  echo "Press enter to continue"
  read a
}

if [ "$DISPLAY" == "" ]; then
  DIALOG="dialog"
else
  DIALOG="dialog"
fi

OPTION=""
TMPFILE="/tmp/$0-$$.item"
TITLE="First Aid Kit quickstart menu"

WIDTH="45"
HEIGHT="15"
MENUHEIGHT="12"
TIMEOUT=60

while [ "x$OPTION" == "x" ]; do
  $DIALOG --timeout "$TIMEOUT" --menu "$TITLE" "$HEIGHT" "$WIDTH" "$MENUHEIGHT" shell "Start shell" fakd "Run diagnostic" reboot "Reboot"  2>$TMPFILE
  if [ "$?" -ne 0 ]; then
    exit 1
  fi

  OPTION=$(cat $TMPFILE)

  if [ "x$OPTION" == "xshell" ]; then
    echo "Starting shell..."
    bash
  elif [ "x$OPTION" == "xfakd" ]; then
    echo "Running diagnostic..."
    firstaidkit -a
    pause
  elif [ "x$OPTION" == "xreboot" ]; then
    reboot
  fi

done
