.\" FirstAidKit 
.TH "FirstAidKit" "1" 
.SH "NAME" FirstAidKit 
.BR
.SH "DESCRIPTION"
firstaidkit executes simple and common recovery tasks in an automated way.  It also has a cli that lets you control firstaidkits behavior

.PP
.SH "BUGS"
.nf
Please report bugs at http://fedorahosted.org/firstaidkit/newticket
.fi

.PP
.SH "AUTHORS"
.nf
Martin Sivak <msivak@redhat.com>
Joel Granados <jgranado@redhat.com>
.fi

.PP
.SH "SEE ALSO"
.nf
http://fedorahosted.org/firstaidkit
.fi

