.TH "FirstAidKit Backup system" "1" 
.SH "NAME" firstaidkit-backup
.BR
.SH "DESCRIPTION"

To abstract the plugin developer from lowlevel backup logic, the
plugins utilize backup object named self._backups. Developer can use
it to backup and restore files and arbitrary chunks of data.

The backup system si also thread safe and ensures integrity of the backups,
so the developer does not have to care about locks and synchronization.

.SH "Requesting a backup storage space"

.SH "Using backup"

.SH "Using restore"

.SH "Developing another backup storage backend"

.SH "SEE ALSO"
firstaidkit-plugin
firstaidkit-reporting
http://fedorahosted.org/firstaidkit

.SH "AUTHORS"
Martin Sivak <msivak@redhat.com>
Joel Granados <jgranado@redhat.com>

.SH "BUGS"
Please search/report bugs at http://fedorahosted.org/firstaidkit/newticket
